name: Terraform-CI

on:
  pull_request:
    branches:
      - main  # Runs CI on pull requests to the main branch

env:
  TF_VERSION: 1.6.6  # Define Terraform version in an environment variable

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Uses the latest version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}  # Uses environment variable for flexibility

      - name: Initialize Terraform
        run: terraform init

      - name: Check Terraform Formatting
        run: terraform fmt -recursive -check -diff  # Shows formatting issues with diffs

      - name: Validate Terraform Configuration
        run: terraform validate